import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="topnav">
          <div className="topnav-inner">
            <a className="nav-brand" href="/">
              Prosequetor
            </a>
            <nav className="nav-links">
              <a href="/">Home</a>
              <a href="/JadwalSidang">Jadwal Sidang</a>
              <a href="/contact">Contact</a>
            </nav>
          </div>
        </header>

        <main className="app-main">{children}</main>
      </body>
    </html>
  );
}
